### ISSUE TITLE
Add `clip` for windows copy to clipboard

### ISSUE THREAD

**Issue by kpym** [tremby/imgur.sh#18]
The default Windows command to copy to the clipboard is `clip`.
So to make this script works also on Windows (with GitBash for example) you can add the following lines: 

```shell
elif type clip &>/dev/null; then
    echo -n "$clip" | clip
```

**Comment by tremby** [comment]
Thanks for this. Can you please test the version in the `windows` branch and verify it works as you expect?

**Comment by kpym** [comment]
Tested, it works ;)
Thanks.

**Comment by tremby** [comment]
Merged that to main and tagged it v10. Thanks for the idea!
