### ISSUE TITLE
No error handling for Imgur response "HTTP error before end of send, stop sending"

### ISSUE THREAD

**Issue by Strolls** [tremby/imgur.sh#2]
Image uploading seems flakey today, imgur.sh gives no error.

I am getting the same results on Mac and linux on one network, and on linux at another site.

Next I tried uploading the same image(s) via Imgur's native web interface - it failed the first time, but worked a few minutes later. It's still not working for me via imgur.sh (at both sites).

I think the cause of the upload failure is that Imgur is acting flakey today, but imgur.sh should give better error handling.

    $ ls
    13554887.jpg  13560798-large.jpg
    $ 
    $ imgur.sh 13554887.jpg 
    
    Delete page: 
    Haven't copied to the clipboard: no xsel, xclip, or pbcopy
    $ apikey="b3625162d3418ac51a9ee805b1840452"                                     
    $ curl -vF "key=$apikey" -H "Expect: " -F "image=@13554887.jpg" http://imgur.com
    /api/upload.xml                                                                 
    * Hostname was NOT found in DNS cache
    *   Trying 185.31.19.193...
    * Connected to imgur.com (185.31.19.193) port 80 (#0)
    > POST /api/upload.xml HTTP/1.1
    > User-Agent: curl/7.39.0
    > Host: imgur.com
    > Accept: */*
    > Content-Length: 54203
    > Content-Type: multipart/form-data; boundary=------------------------2e14a811f0c38497
    > 
    < HTTP/1.1 404 Not Found
    < Content-Type: text/html; charset=utf-8
    < X-Post-Rate-Limit-Limit: 1250
    < X-Post-Rate-Limit-Remaining: 1228
    < X-Post-Rate-Limit-Reset: 1321
    < Cache-Control: max-age=60, stale-while-revalidate=600, stale-if-error=86400, public
    < Accept-Ranges: bytes
    < Fastly-Debug-Digest: aa0b0512927e5582948d16bac6e05e68fc14dacba45a1df9a77350b56609b2ab
    < Transfer-Encoding: chunked
    < Accept-Ranges: bytes
    < Date: Thu, 31 Mar 2016 05:27:59 GMT
    < Connection: keep-alive
    < X-Served-By: cache-iad2129-IAD, cache-lhr6333-LHR
    < X-Cache: MISS, MISS
    < X-Cache-Hits: 0, 0
    < Vary: Accept-Encoding
    < Server: cat factory 1.0
    < X-Frame-Options: DENY
    * HTTP error before end of send, stop sending
    < 
    * Closing connection 0
    $

**Comment by tremby** [comment]
I was keen to keep any error handling as simple as possible, since this is meant to just be a little bash script, not some fully-fledged uploader. But a better message than a blank response would certainly be good.

I never expected a 404, though. This suggests more than just a flaky server to me. I think it's possible they've done a major upgrade, and have finally switched off the v1 API, which this script always relied on.

At one point in the past they did such a rollout and *forgot* to switch the v1 API back on, and soon did. I'll send an email and ask what's up.

Thanks.

**Comment by tremby** [comment]
I never had a response but it looks like the v1 API is permanently gone. The script now uses the v3 API, so this issue is now moot, I believe.
