### ISSUE TITLE
Imgur doesn't copy to clipboard though xsel or xclip alone or both are installed

### ISSUE THREAD

**Issue by zim0369** [tremby/imgur.sh#21]

**Comment by tremby** [comment]
I'm interpreting this as "doesn't copy to clipboard whether xsel is installed, or xclip, or both".

I'll need more details, since it works fine for me.

- `/usr/bin/env bash --version`?
- `xsel --version`?
- `xclip -version`?
- `uname -a`?
- `echo $DISPLAY`?

**Comment by zim0369** [comment]
```
+ GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
+ xsel version 1.2.0 
+ xclip version 0.13
+ Linux arch 5.16.2-zen1-1-zen #1 ZEN SMP PREEMPT Thu, 20 Jan 2022 16:18:31 +0000 x86_64 GNU/Linux
+ :0
+ No error messages

Since the script checks for xsel before xclip so I tried with:
+ Both installed: Nothing copied to clipboard
+ Only xclip installed: Nothing copied to clipboard
+ Both uninstalled: Nothing copied to clipboard & Script outputs "Haven't copied to the clipboard"

My friend using Endeavor OS experienced similar issue with only xsel installed.

**Comment by tremby** [comment]
Could it be that you're trying to paste from the **clipboard** when it's actually being put on the X **selection**? `xsel` (and maybe `xclip` too; I don't remember) uses the selection by default. You can normally paste from the selection with a middle click. `xsel` with no arguments will output the contents of the selection. So try running the imgur script and then right after running `xsel`, and see if it outputs the URL.

**Comment by tremby** [comment]
I've just made a small change to the script so you can set configuration for those programs.

If you want to use the clipboard rather than the selection, and you're using xsel, you can set an environment variable `IMGUR_XSEL_OPTIONS=-b`. You can export that in your `.bashrc` or wherever you like to put environment variables to set it for all your terminal sessions, or you could make a wrapper script.

Let me know if this solves your issue.

**Comment by txtyash** [comment]
> I've just made a small change to the script so you can set configuration for those programs.
> 
> If you want to use the clipboard rather than the selection, and you're using xsel, you can set an environment variable `IMGUR_XSEL_OPTIONS=-b`. You can export that in your `.bashrc` or wherever you like to put environment variables to set it for all your terminal sessions, or you could make a wrapper script.
> 
> Let me know if this solves your issue.

It was my lack of knowledge about clipboards in linux. I should've tested the script with middle click previously. It does paste the link with middle click but still I prefer using `IMGUR_XSEL_OPTIONS=-b`.
