### ISSUE TITLE
Imgur API has changed

### ISSUE THREAD

**Issue by michalrus** [tremby/imgur.sh#3]
The current way to upload seems to be https://api.imgur.com/endpoints/image

The previous endpoint,

```
% curl -Ssf http://imgur.com/api/upload.xml
curl: (22) The requested URL returned error: 404 Not Found
```

returns 404.

See also https://github.com/NixOS/nixpkgs/issues/14444 , https://aur.archlinux.org/packages/imgurbash/ .

**Comment by michalrus** [comment]
If anyone is interested, this one works with the new API → https://github.com/ram-on/imgurbash2

**Comment by tremby** [comment]
Thanks for this. I was waiting to hear back from Imgur about the old API, but given that I haven't, I'm going to go ahead and update my script as soon as I find time.

**Comment by michalrus** [comment]
@tremby, thank you! :smile_cat: The more, the merrier.

**Comment by michalrus** [comment]
Thank you for the fix. :smile_cat:
